[programs.localnet]
program_bitmap = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sssroot/.config/solana/id.json"

[scripts]
test = "yarn anchor:test"
