[programs.localnet]
program_bitmap = "BMP23Y1u4FdGSwknSH7PVswT9ru7f9YsyjqR18pHGmBJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn anchor:test"
