[programs.localnet]
program_bitmap = "EGouPpM75ScRYBos5nYoafDDYVqMJptYQf5oqEoYZ7Xz"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/sssroot/.config/solana/id.json"

[scripts]
test = "yarn anchor:test"
